language: python

branches:
  only:
    - dev
    - master

python:
  - "3.5"

services:
  - docker
  - docker-compose

jobs:
  include:
    - stage: Test
      script:
        - echo "No tests yet"

    - stage: Build and push the weather bot
      script:
      - cd workstreambot/weather
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t amoschatbot/weatherbot:latest .
      - docker push amoschatbot/weatherbot
    - stage:
      script:
      - cd workstreambot/sightseeing
      - docker login -u="DOCKER_USERNAME" -p="DOCKER_PASSWORD"
      - docker build -t amoschatbot/sightseeingbot:latest .
      - docker push amoschatbot/sightseeingbot
