language: python

branches:
  only:
    - dev
    - master

python:
  - "3.5"

services:
  - docker
  - docker-compose

jobs:
  include:
    - stage: test
      if: branch = master
      script:
        - echo "No tests yet"

    - stage: build weatherbot
      script:
      - cd workstreambot/weather
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t amoschatbot/weatherbot:latest .
      - docker push amoschatbot/weatherbot
    - stage: build sightseeinbgot
      script:
      - cd workstreambot/sightseeing
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t amoschatbot/sightseeingbot:latest .
      - docker push amoschatbot/sightseeingbot
    - stage: release
      script:
      - cd workstreambot
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - bash release.sh
