language: python

branches:
  only:
    - dev
    - master
    - persistance_integration

python:
  - "2.7"
  - "3.5"

services:
  - docker
  - docker-compose

jobs:
  include:
    - stage: test
      if: branch = dev
      script:
        - cd workstreambot
        - python -m pytest test/
    - stage: build rasa base
      if: branch = persistance_integration
      script:
      - cd workstreambot/base_rasa_core
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t amoschatbot/rasabase:latest .
      - docker push amoschatbot/rasabase
    - stage: release
      if: branch = master
      script:
      - cd workstreambot
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - bash release.sh
