language: python

branches:
  only:
    - travis-test

python:
  - "3.5"

services:
  - docker
  - docker-compose

jobs:
  include:
    - stage: build weather image
      script:
      - cd workstreambot/weather
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t amoschatbot/chatbot .
      - docker images
      - docker tag weatherbot amoschatbot/weatherbot
      - docker push amoschatbot/chatbot
