language: python

branches:
  only:
    - dev
    - master

python:
  - "3.6.3"

services:
  - docker
  - docker-compose

jobs:
  include:
    - stage: test
      if: branch = dev
      script:
        - cd workstreambot
        - docker build -t amoschatbot/worksteambot:latest .
        - docker run -it --entrypoint bash amoschatbot/worksteambot -a test.sh
    - stage: release
      if: branch = master
      script:
      - cd workstreambot
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - bash release.sh
