version: '3'
services:
  rasa_core:
    container_name: weatherbot
    entrypoint: python -m rasa_core.server -d project/dialogue -u models/nlu/current
    build: weather
    ports:
      - 5005:5005
      - 5000:5000
    expose:
      - 5005
      - 5000
