version: '3'
services:
  workstreambot:
    container_name: workstreambot
    build: .
    ports:
      - 5012:5000
    expose:
      - 5012
    environment:
      - PYTHONUNBUFFERED=0
      
networks:
  default:
    external:
      name: redis-network
